# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctx < Formula
  desc "The universal context package manager for LLM agents"
  homepage "https://getctx.org"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.12.0/ctx-darwin-amd64.tar.gz"
      sha256 "eed960dcdcb1924f028a8e31dc6063aa9932f51d0e915f02a2342438f861ee6c"

      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.12.0/ctx-darwin-arm64.tar.gz"
      sha256 "3172eded761846ef758b3488b03af52def797f0e8a6f8a59fcdd19f93a1152f3"

      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.12.0/ctx-linux-amd64.tar.gz"
      sha256 "8e13761d16352756390f2b8c4f616020917db7bb03f74fe2d9ed2a06eb97c945"
      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.12.0/ctx-linux-arm64.tar.gz"
      sha256 "8a2b378bf971af115053c3e5274db57ece122461e07b71371a12741e4506cb7a"
      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
  end

  test do
    system "#{bin}/ctx", "version"
  end
end
