# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctx < Formula
  desc "The universal context package manager for LLM agents"
  homepage "https://getctx.org"
  version "0.25.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.25.0/ctx-darwin-amd64.tar.gz"
      sha256 "ad073b0c09b08f22acfe916c5199bd32253b9bdccb4ab1f9480df8e771d830d0"

      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.25.0/ctx-darwin-arm64.tar.gz"
      sha256 "adffaa71cab426e7a716811d5f477c173f768f4ae6b025745c8ca300c670cec7"

      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.25.0/ctx-linux-amd64.tar.gz"
      sha256 "fabd7527eebc5444474a6fa38013f047f5d75a4a4b8c697fb95ce5a49f752426"
      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ctx-hq/ctx/releases/download/v0.25.0/ctx-linux-arm64.tar.gz"
      sha256 "71d2549416ae1e33a9ee3df7eb09fed101cb6a4d9d91faca325b295af5a7de6c"
      define_method(:install) do
        bin.install "ctx"
        bash_completion.install "completions/ctx.bash" => "ctx"
        zsh_completion.install "completions/_ctx"
        fish_completion.install "completions/ctx.fish"
      end
    end
  end

  test do
    system "#{bin}/ctx", "version"
  end
end
